Bluerov2 heavy revisions
evan-palmer/bluerov2_ignition pull request #1
Opened 2023-07-06 15:54 UTC by ssicari

I have been using the BlueROV2 repos and made revisions based on Clydes' review of Evan's PR

2023-07-07 03:59 UTC, evan-palmer commented
Thanks for adding these changes! I'm away for most of the week, but I will get a review in early next week (probably on Monday)

2023-07-11 01:16 UTC, evan-palmer requested changes
Thanks again for taking on these changes! This is super helpful

2023-07-11 01:16 UTC, evan-palmer commented on scripts/down.sh
> +gz topic -t /model/$1/joint/thruster7_joint/cmd_thrust -m gz.msgs.Double -p 'data: 5'
It might be worth adding a condition here to check which frame is used and decide when to send the thruster 7 & 8 commands according to that. I don't see any bugs in this implementation, but it may be less readabilty for folks that are new to the project.

2023-07-11 01:16 UTC, evan-palmer commented on scripts/up.sh
> +gz topic -t /model/$1/joint/thruster7_joint/cmd_thrust -m gz.msgs.Double -p 'data: -5'
Same comment as the `down.sh` script.

2023-07-11 01:16 UTC, evan-palmer commented on scripts/generate_model.py
> +    #fluid_density: float = 998, moved to config files
So Clyde's comment here was also discussing removing the global variable on line 58, and passing the value read from the configuration file to this method. So the fix for that comment would look more like parsing the `fluid_density` configuration from the configuration file in the `get_model_params_from_config` method, then passing that to the `ModelParams` constructor and using the value in the call to `thrust_to_ang_vel` in the constructor

2023-07-11 01:16 UTC, evan-palmer commented on worlds/bluerov2_heavy_underwater.world
> +  <world name="bluerov2_heavy">
I am checking with Clyde on whether or not the filenames should be updated as well. Here is the link to the thread: https://github.com/clydemcqueen/bluerov2_ignition/pull/9#discussion_r1259063846

2023-07-13 14:15 UTC, ssicari commented
> Thanks again for taking on these changes! This is super helpful

When using the manual controls in the ardusub cli, such as arm throttle rc 5 500, thrusters 7 and 8 don't seem to be moving the rov at all on the heavy frame. Do you encounter this as well? Thank you

2023-07-13 20:13 UTC, evan-palmer commented
>
> When using the manual controls in the ardusub cli, such as arm throttle rc 5 500, thrusters 7 and 8 don't seem to be moving the rov at all on the heavy frame. Do you encounter this as well? Thank you

I just tested it out, and it looks like it's working as expected. If I run,

```bash
arm throttle
rc 3 1495
```

The BlueROV2 moves down as expected. Also, I just pushed a couple small remaining fixes. Would you be willing to pull those and verify that they work on your end as well? If they do, then I will make one more pass and it should be good to merge!

2023-07-13 23:00 UTC, ssicari commented
Yes I can look at the changes either get to those later tonight or early tomorrow morning. As for the thrusters, thrusters 1-6 work for me but if I run,arm throttle rc 7/8 1450the heavy configuration model does not move for me.Thank youOn Jul 13, 2023, at 16:13, Evan Palmer ***@***.***> wrote:﻿

When using the manual controls in the ardusub cli, such as arm throttle rc 5 500, thrusters 7 and 8 don't seem to be moving the rov at all on the heavy frame. Do you encounter this as well? Thank you

I just tested it out, and it looks like it's working as expected. If I run,
arm throttle
rc 3 1495
The BlueROV2 moves down as expected. Also, I just pushed a couple small remaining fixes. Would you be willing to pull those and verify that they work on your end as well? If they do, then I will make one more pass and it should be good to merge!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-13 23:11 UTC, evan-palmer commented
> Yes I can look at the changes either get to those later tonight or early tomorrow morning. As for the thrusters, thrusters 1-6 work for me but if I run, ```bash arm throttle  rc 7/8 1450 ``` the heavy configuration model does not move for me. Thank you

Ahh I see. When sending those RC commands, ArduSub does some mixing on the backend to distribute the commands to the respective thrusters. So when you are sending RC commands using the CLI, [this](https://www.ardusub.com/developers/rc-input-and-output.html) is the mapping used. In this case, we wouldn't expect RC 7/8 to do anything because those channels are mapped to the camera servoing.

2023-07-14 17:08 UTC, ssicari commented
> > Yes I can look at the changes either get to those later tonight or early tomorrow morning. As for the thrusters, thrusters 1-6 work for me but if I run, `bash arm throttle  rc 7/8 1450 ` the heavy configuration model does not move for me. Thank you
> 
> Ahh I see. When sending those RC commands, ArduSub does some mixing on the backend to distribute the commands to the respective thrusters. So when you are sending RC commands using the CLI, [this](https://www.ardusub.com/developers/rc-input-and-output.html) is the mapping used. In this case, we wouldn't expect RC 7/8 to do anything because those channels are mapped to the camera servoing.

Ok I see. I just pulled and checked the changes and they work fine for me. Without the frame checking though you can run the down or up script with 
```bluerov2_heavy vectored```
for example, and it still responds. Meaning you can run the script with a mismatching model and frame but I don't think that will run into many problems as it still goes based on what model is currently loaded and the usage no longer states to add a frame when you run it.

2023-07-14 20:32 UTC, evan-palmer approved these changes

2023-07-14 20:33 UTC, evan-palmer commented
> 
> Ok I see. I just pulled and checked the changes and they work fine for me. Without the frame checking though you can run the down or up script with `bluerov2_heavy vectored` for example, and it still responds. Meaning you can run the script with a mismatching model and frame but I don't think that will run into many problems as it still goes based on what model is currently loaded and the usage no longer states to add a frame when you run it.

Great! I just did a quick check and it all looks good to merge. I'll merge this and ping Clyde with the updates

2023-07-14 20:34 UTC, merged